Install required clang-fromat version.

diff --git a/script/check-style b/script/check-style
--- a/script/check-style
+++ b/script/check-style
@@ -20,12 +20,17 @@ ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
 
 CLANG_FORMAT="$(which clang-format)" || CLANG_FORMAT="${HOME}/clang/bin/clang-format"
 
-CLANG_FORMAT_VERSION="$(${CLANG_FORMAT} -version | cut -d ' ' -f 3)"
-CLANG_FORMAT_VERSION_REQUIRED="3.8.0"
-if [[ "${CLANG_FORMAT_VERSION}" != "${CLANG_FORMAT_VERSION_REQUIRED}" ]]; then
-  echo "Skipping: clang-format ${CLANG_FORMAT_VERSION_REQUIRED} required."
-  echo "Current version: ${CLANG_FORMAT_VERSION}"
-  exit 0
+CLANG_VERSION="$(${CLANG_FORMAT} -version | cut -d ' ' -f 3)"
+CLANG_VERSION_REQUIRED="3.8.0"
+if [[ "${CLANG_VERSION}" != "${CLANG_VERSION_REQUIRED}" ]]; then
+  echo "Current version: ${CLANG_VERSION}"
+  CLANG_DIRECTORY=$(mktemp -d /tmp/clang_XXXXX)
+  echo "Installing required clang-format ${CLANG_VERSION_REQUIRED} to ${CLANG_DIRECTORY}"
+  curl --silent --show-error --retry 10 \
+    "http://releases.llvm.org/${CLANG_VERSION_REQUIRED}/clang+llvm-${CLANG_VERSION_REQUIRED}-x86_64-linux-gnu-debian8.tar.xz" \
+    | tar Jx -C "${CLANG_DIRECTORY}" --strip=1 \
+  && CLANG_FORMAT="${CLANG_DIRECTORY}/bin/clang-format" \
+  || { echo "Could not install required clang-format. Skip formating." ; exit 0 ; }
 fi
 
 pushd ${ROOT} > /dev/null
